[package]
name = "vulkan_stuff"
version = "0.1.0"
authors = ["Vincent Stakenburg <vincentstakenburg@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.11.1"
winit = "0.18.0"
vulkano-win = "0.11.1"
vulkano-shaders = "0.11.1"
stl_io = "0.4.0"

cgmath = "0.17"
image = "0.21"
time = "0.1.38"
